mvc_SoccerLigas/mvc_SoccerLigas/Models/Ligues.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Xml.Serialization;

namespace mvc_SoccerLigas.Models
{
    [Serializable]
    [XmlRoot("Category"), XmlType("Name")]
    public class Ligues
    {
        public string category { get; set; }
        public string name { get; set; }
        public string gid { get; set; }
        public string id { get; set; }
        public string file_group { get; set; }
        public string iscup { get; set; }
        public string matches { get; set; }
        public string date { get; set; }
        public string formatted_date { get; set; }
        public string time { get; set; }
        public string LTeam { get; set; }
        public string VTeam { get; set; }
        public string ftScore { get; set; }
    }
}

mvc_SoccerLigas/mvc_SoccerLigas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc_SoccerLigas.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

mvc_SoccerLigas/mvc_SoccerLigas/Controllers/LigueController.cs
using mvc_SoccerLigas.Models;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using System.Xml.Linq;

namespace mvc_SoccerLigas.Controllers
{
    public class LigueController : Controller
    {
        // GET: Ligue
        public ActionResult Index()
        {
            DataSet ds = new DataSet();
            List<SelectListItem> dropDownList = new List<SelectListItem>();

            string xmlData = Server.MapPath("~/App_Data/soccer.xml");
            ds.ReadXml(xmlData);

            var SLigue = new List<Ligues>();

            SLigue = (from rows in ds.Tables["category"].AsEnumerable()
                      select new Ligues
                      {
                          name = rows["name"].ToString(),
                          id = rows["category_id"].ToString()
                      }).ToList();
            foreach (var item in SLigue)
            {
                dropDownList.Add(new SelectListItem() { Text = item.name, Value = item.id });
            }

            ViewBag.DropDownValues = dropDownList;
            return View();
        }
        [HttpGet]
        public JsonResult GetDetailsLiga(int? pId)
        {

            List<Ligues> SLigue = new List<Ligues>();
            try
            {
                DataSet ds = new DataSet();
                string xmlData = Server.MapPath("~/App_Data/soccer.xml");
                ds.ReadXml(xmlData);


                SLigue = (from m in ds.Tables["match"].AsEnumerable()
                          join lt in ds.Tables["localteam"].AsEnumerable() on m.Field<int>("match_id") equals lt.Field<int>("match_id")
                          join lv in ds.Tables["visitorteam"].AsEnumerable() on m.Field<int>("match_id") equals lv.Field<int>("match_id")
                          //join ht in ds.Tables["ht"].AsEnumerable() on m.Field<int>("match_id") equals ht.Field<int>("match_id")
                          join ft in ds.Tables["ft"].AsEnumerable() on m.Field<int>("match_id") equals ft.Field<int>("match_id")
                          //join et in ds.Tables["et"].AsEnumerable() on m.Field<int>("match_id") equals et.Field<int>("match_id")
                          where m.Field<int>("matches_id").Equals(pId)
                          select new Ligues
                          {
                              time = m["time"].ToString(),
                              formatted_date = m["formatted_date"].ToString(),
                              LTeam = lt["name"].ToString(),
                              VTeam = lv["name"].ToString(),
                              ftScore= ft["score"].ToString()

                          }).ToList();

            }
            catch (System.Exception ex)
            {
                ViewBag.msgError = ex.InnerException.ToString() + "-" + ex.Message.ToString();
                throw;
            }
            return Json(new { SLigue }, JsonRequestBehavior.AllowGet);
        }
    }
}

mvc_SoccerLigas/mvc_SoccerLigas/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

mvc_SoccerLigas/mvc_SoccerLigas/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

mvc_SoccerLigas/mvc_SoccerLigas/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

mvc_SoccerLigas/mvc_SoccerLigas/Views/Ligue/Index.cshtml
@model IEnumerable<mvc_SoccerLigas.Models.Ligues>

@{
    ViewBag.Title = "Index";

}

<h2>Index</h2>

<div class="panel panel-default">
    <div class="panel-heading">Detalles Ligas Internacionales</div>
    <div class="panel-body">
        @Html.DropDownList("DropDownValues", ViewBag.DropDownValues as SelectList, "Selecciona una Liga", new { @class = "form-control dropdown" })
    </div>
    <div class="panel-body">
        <div id="tbl_matches"></div>
    </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-1.10.2.js"></script>


<script type="text/javascript">

    $(document).ready(function () {

        $(".mod").click(function () {

            $("#myModal").modal('show');

        });

    });
    $(document).ready(function () {


        $("#DropDownValues").change(function () {
            var a = $("#DropDownValues Option:Selected").val();

            $.ajax(
                {
                    type: "GET",
                    contentType: "application/json;charset=utf-8",
                    url: "/Ligue/GetDetailsLiga?pId=" + a,
                    dataType: "json",
                    success: function (data) {
                        var tabla = "<table class='table table-bordered table-condensed table-hover table-responsive table-striped text-primary'><tr>"
                        tabla += "<th>Equipo Local</th>"
                        tabla += "<th>Score</th>"
                        tabla += "<th>Equipo Visitante</th>"
                        tabla += "<th>Fecha</th>"
                        tabla += "<th>Hora</th>"
                        tabla += "</tr>"
                        var len = data.SLigue.length;
                        for (var i = 0; i < len ; i++) {
                            tabla += "<tr>";
                            tabla += "<td><a id=id_" + data.SLigue[i].LTeam + "data-toggle='modal' data-target='#myModal' role='button' class='mod'>" + data.SLigue[i].LTeam + "</a></td>"
                            tabla += "<td>" + data.SLigue[i].ftScore + "</td>"
                            tabla += "<td><a id=id_" + data.SLigue[i].VTeam + ">" + data.SLigue[i].VTeam + "</a></td>"
                            tabla += "<td>" + data.SLigue[i].formatted_date + "</td>"
                            tabla += "<td>" + data.SLigue[i].time + "</td>"
                            tabla += "</tr>";
                        }
                        tabla += "</tabla>"
                        $("#tbl_matches").empty().html(tabla);
                    },
                    error: function (e1, e2, e3) {
                        alert(e3)
                    }
                });
        });
    });

</script>

mvc_SoccerLigas/mvc_SoccerLigas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ligas Internacionales", "Index", "Ligue", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ligas", "Index", "Ligue")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ECS</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>